#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input low lkprint/printerserial || true
db_input low lkprint/printerparallel || true
db_input medium lkprint/apiurl || true
db_input high lkprint/apitoken || true
db_input high lkprint/awsid || true
db_input high lkprint/awssecret || true

db_go